# Build stage
FROM node:16-alpine as builder
WORKDIR /app
COPY . /app/
RUN npm install
RUN npm run build  # Assuming this script properly builds the frontend as part of its process
EXPOSE 8080
ENTRYPOINT ["tail", "-f", "/dev/null"]

# Production stage
#FROM nginx:stable-alpine
#COPY --from=builder /app/dist /usr/share/nginx/html
#EXPOSE 8080
#CMD ["nginx", "-g", "daemon off;"]
