# https://hub.docker.com/_/mongo
version: '3.8'

services:
  mongo:
    image: mongo
    hostname: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

#   frontend:
#     build:
#       context: .
#       dockerfile: Dockerfile.frontend
#     ports:
#       - "8080:8080"
#     depends_on:
#       - backend
#     restart: always

#   backend:
#     build:
#       context: .
#       dockerfile: Dockerfile.backend
#     ports:
#       - "3000:3000"
#     depends_on:
#       - mongo
#     restart: always
#     environment:
#       - NODE_ENV=production

#   nginx:
#     image: nginx:stable-alpine
#     ports:
#       - "8080:8080"
#     volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#       - ./frontend/dist:/usr/share/nginx/html
#     depends_on:
#       - frontend
#       - backend
#     restart: always

# networks:
#   default:
#     name: mynetwork